name: PeyangBridge

on: push

jobs:
  develop2peyang:
    runs-on: ubuntu-latest
    if: "github.ref == 'refs/heads/develop'"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Fix code
        uses: getsentry/action-eslint-fix@v1
      
      - name: commit
        uses: EndBug/add-and-commit@v4
        with:
          author_name: Eslint BOT
          message: Code Fix
          force: true
          branch: peyang
